sudo: required
language: go
dist: bionic 

go:
- 1.13.5

before_script:
  - git clone --depth 1 -b "v0.6.1" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh

script:
  - ./install.sh
  - ./test.sh
